--- 
version: "3.1"
secrets: 
  psqlpass: 
    external: true
services: 
  drupal: 
    image: drupal
    ports: 
      - "5000:80"
    volumes: 
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
  postgres: 
    environment: 
      - POSTGTES_PASSWORD_FILE=/run/secret/psqlpass
    image: postgres
    secrets: 
      - psqlpass
    volumes: 
      - drupal-data:/var/lib/postgresql/data

volumes: 
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:

